### ISSUE TITLE
Port ?

### ISSUE THREAD

**Issue by Bennyboy1695** [MultiChat/Development#1]
I know 1.7 is going out of existence but is there any chance you could backport this to 1.7 ? we love the plugin but it doesn't seem to get prefix and stuff correctly on the 1.7 servers.

**Comment by Bennyboy1695** [comment]
Or barring that make it work with LuckPerms as that what we use for prefix's 😛

**Comment by OllieMartin** [comment]
Hey there, are you using vault on the 1.7 servers? That would also be dependent on you using Spigot over sponge. If you are using either Spigot or Sponge though LuckPerms is supported so it should be working. However if you are using the BUNGEE version of LuckPerms there have been some issues which I am currently looking into! Sorry it took so long for me to reply, this is the first message Ive had through the github! So yeah if you could send me any extra info about your server Ill happily see what I can do! :)

**Comment by Bennyboy1695** [comment]
Yes it's 1.7 thermos servers with vault version : 1.4.1. the plugin works perfectly the only issue is on the 1.7 servers the prefixes aren't showing correctly. For example i set a test prefix literally just saying Test and that showed, but once removed the prefix didn't actually leave from in-front of my name as far as chat could see and trying to add higher priority prefix's didn't help either. We are using bungee version of LuckPerms aswell as the server side, but it wouldn't show pex prefix'es on 1.7 either.

**Comment by OllieMartin** [comment]
Sorry for the slow response. It seems very odd to me that it shows originally but then doesn't update. Out of interest does it update if you send more than one chat message, or if you re-log? I will try and fix this up ASAP.

**Comment by Bennyboy1695** [comment]
No none of that fixes it, i did try everything i could think of when i tested it. Even restarts made the test prefix stay, only when i disabled and re-enabled the mod during restarts would the prefix remove

**Comment by OllieMartin** [comment]
Hey so Ive been playing around with luckperms. I know this is probably a really stupid question to ask but I thought id make sure... Are you actually removing the prefixes? So for example, if I have my standard prefix at priority 5 say, and I added "TEST" also at priority 5, then I would have both showing, that is how luckperms works. But then to remove the "TEST" prefix I do /lp user Revilo410 meta removeprefix 5 TEST. MultiChat usually takes 1 chat message to update as the new data has to be communicated to the bungeecord server, but after Ive sent 1 message my prefix from luckperms definitely updates properly. I shall keep looking though in case I find something else! :)

**Comment by OllieMartin** [comment]
I have released a snapshot version of 1.4 to try and fix many small issues such as the one you are having, please give it a go and let me know if it fixes anything :) If it doesnt then I will keep working on it!

https://github.com/MultiChat/Development/blob/master/multichat/target/multichat-1.4.jar

**Comment by OllieMartin** [comment]
That link above should now point to an even newer download which I am 99% sure will work for you, only one way to find out! :D

**Comment by Isolonice** [comment]
Hello,

Using lastest snapshot and managed to get prefixes works with luckpems.

Used this commit: https://github.com/SpigotMC/BungeeCord/issues/1335

Then need to put the .jar on every servs + bungee, turn on fetch option. Working on Sponge 1.10.2 + Thermos 1.7.10 + Spigot 1.10.

**Comment by OllieMartin** [comment]
Hey, glad to see it works in that case! And thanks for verifying it. Ill close up this issue, if there are any issues let me know :)

**Comment by Bennyboy1695** [comment]
I keep getting this error in bungee no matter the version and after doing what Isolonice has said to do http://i.imgur.com/ZfwG0Ex.png

**Comment by OllieMartin** [comment]
Hmm thats weird, Ill take a look and see if I can find anything that could be causing it :)

**Comment by Bennyboy1695** [comment]
Thanks, would love this to work as we need something to link chat between sponge and thermos and something with global and local which yours is the only plugin i've found so far 😛

**Comment by OllieMartin** [comment]
Ummm, I was trying to look to find what throws that error message in my code and um, nothing does... lol

Are you on the latest snapshot version of MultiChat?

**Comment by OllieMartin** [comment]
Latest snapshot: https://github.com/MultiChat/Development/blob/master/multichat/Versions/1.4/1.4.0/Snapshots/MultiChat%201.4%20Snapshop%2010.jar

**Comment by OllieMartin** [comment]
MultiChat 1.4 has been released please give it a go to see if it works for you. Remember to put it in every spigot server as well :)
