### ISSUE TITLE
Check local contexts for things like link and color perms

### ISSUE THREAD

**Issue by itsmeow** [MultiChat/Development#101]
**Is your feature request related to a problem? Please describe.**
I have ranks defined on per-server contexts which I would like to grant permission to use links in chat. However, this is not possible as if the rank is on a server context, MultiChat checks the bungee context causing the permission check to fail.

**Describe the solution you'd like**
Possibly check the player's local context for permissions (or make a config option for such) so that a system like that will work.

**Describe alternatives you've considered**
I could redo my ranks to be global with per-server perms but it's a lot of work and I think this solution is needed anyway.

**Comment by OllieMartin** [comment]
Hi, thank you for the issue.

However, I would argue it is not the job of a bungeecord plugin to go and check permissions from Spigot when so many permission managers exist that support bungeecord.

It is very simple to set up bungeecord ranks that would allow your players of different ranks to use the chat colours in different contexts. It is no secret that LuckPerms is the best permission manager at the present time. With LuckPerms you can sync your local server permissions with bungeecord and set contexts even for these bungeecord permissions.

For example, you can say that a player only has access to a specific bungeecord permission when they are in a certain server context.

MultiChat is evolving a lot, and it is possible that more of the plugin will begin to exist in the local spigot part. But at its heart MultiChat is a bungeecord chat management system, and when you use a bungeecord network you should be using a rank system that supports bungeecord.

I know this is probably not the answer you want to hear, I am more than happy to discuss the idea with you further. But at the moment I believe this is the job of the permissions plugin and not of MultiChat.

**Comment by itsmeow** [comment]
I understand. I know how to use LuckPerms, however my foolish past self did not consider the repercussions of setting my ranks to be server-specific due to the bungeecord nature of MultiChat. However, I still think this is an important feature to be implemented at some point as currently MultiChat is not context aware because it only checks the Bungee context, thus defeating the points of contexts within LuckPerms.

I understand the implications and requirements of sending all the messages to servers but overall I think it is advantageous. Say I wanted links to only be allowed from a specific world. As of current, that is not possible.

If I could explain my ranks: I wrote a plugin myself to give out points every minute that expire after 1mo, and built a config system to execute commands on certain point values, meaning you need a certain monthly playtime. However, a week ago or so I decided I wanted the ranks to be specific to one server, so I appended server=survival to ALL of the ranks and manually converted all my existing player's ranks to server=survival. Thus my issue. This way, I will have to go back and undo that, and then set all the individual permissions on each rank to a specific context, AND THEN finally put the link permission.
Either way, it's a lot of work for both of us, so I suppose it's a question of who will do it xD

I suppose either solution is acceptable, but I still believe that this feature on its own would be advantageous.

**Comment by OllieMartin** [comment]
"Say I wanted links to only be allowed from a specific world. As of current, that is not possible."

I understand your problem, however I believe your statement I have quoted above is false. I believe that you can define contexts on LuckPerms even through the Bungeecord part of the plugin.

This is an example of code I ran in my console:

``` lpb creategroup testgroup
[18:21:54 INFO]: CONSOLE executed command: /lpb creategroup testgroup
[18:21:54 INFO]: [LP] testgroup was successfully created.
> lpb group testgroup permission set multichat.chat.link true world="spawn" server="lobby"
[18:22:30 INFO]: CONSOLE executed command: /lpb group testgroup permission set multichat.chat.link true world="spawn" server="lobby"
[18:22:30 INFO]: [LP] Set multichat.chat.link to true for testgroup in context server="lobby", world="spawn".```

This is a bungeecord permission, set on LuckPerms bungee, but it will only apply when that server has the context server="lobby", world="spawn".

So MultiChat is in fact context aware. But it depends how the ranks are configured.

I feel as though we could come up with a solution to your problem using the functionality already present in LuckPerms. If you could let me know a bit more about exactly what you want to achieve then I will be happy to help!

And if I cannot figure out a way then I will admit defeat haha.

**Comment by itsmeow** [comment]
The goal is to get people able to use links either globally (on all server contexts) or locally (only on survival context) on a rank applied to a user on a server=survival context.

**Comment by OllieMartin** [comment]
Oh right, I see what your issue is.

You have assigned the rank only on one server, but want people of that rank to be able to use links on all servers?

There are a few ways I think you could sort this out.

The correct way is to do the task you do not want to lol. By setting the individual permissions from the rank to a certain context. (Remember LuckPerms can do bulk updates so it might not be quite as tedious as you think.)

The other way would be to create a separate rank you could assign to people globally. Do you want everyone on your server to be able to use links?

I think I need a bit more information about exactly what permissions you are trying to assign from MultiChat, for who, and where they should be able to access it.

**Comment by itsmeow** [comment]
Actually.... the idea of a separate rank makes far more sense as I can just easily add a second event to occur at x points to add a global rank allowing links. So... problem solved. Sorry to waste your time.

**Comment by OllieMartin** [comment]
Thats no problem at all! Glad you have a solution. Let me know if you need anything else :)
