### ISSUE TITLE
Nickname formatting permissions

### ISSUE THREAD

**Issue by itsmeow** [MultiChat/Development#102]
Hi, it's me again :3 With a feature idea

**Is your feature request related to a problem? Please describe.**
I would like to grant select players access to use formatting in nicknames, however currently giving formatting also grants intrusive types like underlines or magic.

**Describe the solution you'd like**
I would like some sort of permission node for each individual formatting type, like `multichat.nickname.format.magic` or `multichat.nickname.format.bold`

**Describe alternatives you've considered**
An alternative maybe some sort of regex rules with permissions for nicknames, as this would also allow filtering profanity and such inside nicknames.

**Comment by OllieMartin** [comment]
Hi,

I will look into adding some extra permissions for you :)

I was going to suggest using the nickname blacklist but it wouldnt work because the formatting codes are stripped before checking that.

**Comment by OllieMartin** [comment]
This is added in v1.9.2 which will be released soon.

    Added permissions for individual types of format codes in nicknames (multichatlocal.nick.format.bold/italic/underline/strikethrough/obfuscated/reset) (multichatlocal.nick.format still grants permissions to ALL types of format codes)
