### ISSUE TITLE
BungeeCord plugin API request

### ISSUE THREAD

**Issue by cnaude** [MultiChat/Development#11]
Hi,

I'd like to see an API that I can hook into for sending and receiving messages. A simple message event would be great. And maybe a documented method of sending messages.

**Comment by OllieMartin** [comment]
Hi there,

Sincere apologies for the ridiculously long delay and I realise by this point you may not even need help anymore.

I have only just had the time to get back into the swing of MultiChat and I have resumed work on the new version 2.0. In this I am hoping to make an API exactly like you've suggested. So should this be something you were still interested in, its coming, hopefullt soon! :)

Best Regards and again apologies for the unacceptably long delay,
Oliver
