### ISSUE TITLE
Allow the name to not be exact in order to whisper to someone

### ISSUE THREAD

**Issue by Pemigrade** [MultiChat/Development#116]
**Is your feature request related to a problem? Please describe.**
Essentials has a feature where if someone had the username "XtacoX", a user could whisper to "taco" and the whisper would go to XtacoX. Unfortunately, players cannot do this with multichat. If the user "XtacoX" has the nickname "pizza", a user could also whisper to "pizza" and the whisper would still go to XtacoX.

**Describe the solution you'd like**
I'd like the plugin to be able to whisper to names that are similar and not identical. In order to accomplish this, essentials uses a feature where whispers find a user as long as that string is in either their username or their nickname. For instance, whispering to "a" would send the whisper to everyone with "a" either in their nickname or their username. Obviously, this can get pretty spammy if someone whispers to "a" and there are dozens of players online. It'd be great if there was a way to set the minimum string length in the config. A minimum length of 3 would be really nice as a default.

I understand that multichatlocal handles nicknames and multichatbungee handles whispers, so I don't know if being able to use whispers to nicknames would even be possible the way the plugin is currently created. Multichatbungee would have to be able to connect to the multichatlocal MySQL db used for nicknames. 

**Describe alternatives you've considered**
I've tried using another plugin for the sole purpose of whispering to nicknames, Unfortunately, none work...

**Comment by OllieMartin** [comment]
This has just been implemented in v1.10 :) It will be available in the next beta release!
