### ISSUE TITLE
Change Hex Code Formatting

### ISSUE THREAD

**Issue by Pemigrade** [MultiChat/Development#119]
**Is your feature request related to a problem? Please describe.**
Essentials uses the format &#[hex code] for message colors. Since Essentials is the most popular chat plugin, other plugins are coded to use the essentials hex codes.

For example, DiscordSRV would turn "&#ffff00banana" in-game to "banana" in the Discord chat, as intended. With MultiChat's formatting, DiscordSRV turns "&x&f&f&f&f&0&0banana" into "&xbanana" in the Discord chat. BungeeTabListPlus also has this problem.

Additionally, typing "&x&f&f&f&f&0&0banana" is a lot more confusing than typing "&#ffff00banana." The problem is compounded when creating a gradient. For example, typing "&x&0&0&0&0&0&0g&x&2&2&2&2&2&2r&x&4&4&4&4&4&4a&x&6&6&6&6&6&6d&x&8&8&8&8&8&8i&x&a&a&a&a&a&ae&x&c&c&c&c&c&cn&x&e&e&e&e&e&et" takes a lot longer and is much more confusing than typing "&#000000g&#222222r&#444444a&#666666d&#888888i&#aaaaaae&#ccccccn&#eeeeeet"

**Describe the solution you'd like**
I'd like to change hex code formatting to &#[hex code] instead of &x&[first character of hex code]&[second character of hex code] ... &[sixth character of hex code]

**Describe alternatives you've considered**
I could revert to EssentialsChat, but MultiChat is intended to replace it rather than accompany it, I think.

Edit: it looks like other players want this suggestion as well: https://discordapp.com/channels/481484944942694401/695328540815786014/727913757103095828

**Comment by OllieMartin** [comment]
I am working on a solution to this :) There are many methods currently being used.

Spigot has support for &x&f&f&f&f&f&f built in, and MultiChat now fully support this in 1.9.3 which I am working on at the moment. DiscordSRV should also have support for this style of codes as it is the spigot default. However, I agree it is very verbose and I am now looking for a way to make it easier using the &#[hexcode] style, (and possibly also the &x[hexcode] style which is also being used by some plugins).

**Comment by Pemigrade** [comment]
Sounds good! The reason I ask is because BTLP and Essentials both use &#rrggbb formatting, so players currently appear as &x[name] in both the tablist and in the Essentials server join message when they log on. DiscordSRV started supporting the &x formatting a day or so before I made this issue :)

Thanks for your work!

**Comment by OllieMartin** [comment]
I believe that this is now fixed, I will release v1.9.3 ASAP :)
