### ISSUE TITLE
Some messages arent registering with spigot plugins

### ISSUE THREAD

**Issue by michaeldriskell** [MultiChat/Development#12]
When players try to redeem McMMO credits, they have to type in chat how many they want to use, and the GuiRedeemMcmmo plugin isnt receiving any of the messages. So they cant redeem points. This started as soon as I installed multichat.

http://imgur.com/a/XRzeo

**Comment by OllieMartin** [comment]
Hi there,
---
I am currently making an effort to sort out all the old issues reported with the plugin. Most of these are very old so will be marked as closed. If you still use the plugin and it is a valid error on the latest versions, then please open a new issue or get in touch with me. Thank you.
---
This is a known issue with ALL bungeecord chatting plugins. (BungeeChat, MultiChat etc. etc.) Unfortunately they have to cancel the chat message on the bungee server, which means its never passed to the spigot server (to stop it being shown twice). This is what causes the issue you are talking about.

In the upcoming version 1.6 of the plugin there is a command to bypass multichat and force chat to be sent to spigot for exactly this purpose. This however is just a short term solution. For the version AFTER 1.6, I am looking to develop a way of making MultiChat work with all spigot plugins that use chat in this way.

That will prevent this error, and MANY many others!

Sorry for the unacceptably long response time, I am just making a point of closing old issues as I have been doing a lot of work on the plugin lately.

Best Regards,
Oliver

**Comment by OllieMartin** [comment]
https://www.spigotmc.org/resources/multichat.26204/update?update=265306

The above update fixes this issue once and for all
