### ISSUE TITLE
&x is counted in nickname length

### ISSUE THREAD

**Issue by Pemigrade** [MultiChat/Development#120]
**Describe the bug**
&x is counted as two characters in a nickname, even though "nickname_length_limit_formatting" should make &x count as no characters. For example, &x&f&f&f&f&0&0banana counts as 8 characters.

**To Reproduce**
1. Use the default nickname limit (15 characters)
2. Type /nick &x&f&f&f&f&0&0FifteenCharNick

**Expected behavior**
The nickname should be set successfully since it is only 15 characters.

**Comment by OllieMartin** [comment]
This is fixed in v1.9.3 which is in progress :) Thank you for the Issue.

I hope to release it ASAP.
