### ISSUE TITLE
Players can use the & character, even though nicknames are intended to be alphanumeric

### ISSUE THREAD

**Issue by Pemigrade** [MultiChat/Development#122]
**Describe the bug**
Players can name themselves something like &&& or &_&

**To Reproduce**
1. Type /nick &_&

**Expected behavior**
You should be unable to use & in your nickname

**Additional context**
You can make nicknames with & in the nickname blacklist by creating the regex rule .*&[g-wG-W|y-zY-Z|&|_].*

However, adding that rule to the nickname blacklist means that I cannot utilize a previous regex rule I created which stops players from using hex codes in their nicknames unless they have permissions to.

**Comment by OllieMartin** [comment]
The reason for this is that the & character was required to be allowed for colour codes. I have replaced the old regex which allowed simple nicknames of: ^[a-zA-Z0-9&_]+$ with a new one that only allows the & character if it is used with colour codes: ^([a-zA-Z0-9_]|(?i)(\\&[0-9A-FL-ORX]))+$

MultiChat then handles if players have permission to use the colour codes in the nickname or not separately.

I hope that helps! They will no longer be able to call themself &_& etc.

It will be part of v.1.9.3 coming soon
