### ISSUE TITLE
Stopping banned/immediately reconnecting players from spamming the "joined the network" message.

### ISSUE THREAD

**Issue by K1569GHENT** [MultiChat/Development#123]
![image](https://user-images.githubusercontent.com/32303261/86521464-57a0b600-be51-11ea-990f-6ee65a6427cb.png)

**Comment by K1569GHENT** [comment]
issue #123 yes babyyyy

**Comment by OllieMartin** [comment]
The only reason this occurs is for 1 of 2 reasons:

(1) You are using a spigot/sponge side banning / whitelist system which is really incompatible with running a bungeecord network for this exact reason. Players can join your network and will then be later kicked by the individual server. The solution is to move your ban / whitelist management to bungee.

(2) You are using a bungeecord banning / whitelist system which is setup incorrectly. I have however made a change in MultiChat v1.9.3 to make it even more compatible with these plugins than it was before to guarantee that as long as those plugins are handling the login at least somewhat correctly then MultiChat will not show the message. MultiChat already only shows the join message on the "PostLoginEvent" which means "After Login". If a player logs into the network then it is clear that multichat should show a network join message.

I'm sorry this is not necessarily the solution you are hoping for, but as far as I am aware MultiChat is acting exactly as it should so as to not cause incompatibilies with any other plugin.

Please feel free to reach out if I am mistaken. I am willing to work with other developers to see what solutions we can arrive at.
