### ISSUE TITLE
RGB does not work for network quit messages

### ISSUE THREAD

**Issue by Pemigrade** [MultiChat/Development#131]
**Describe the bug**
RGB codes do not work for network quit messages. It works fine for network join messages.

**To Reproduce**
1. Set the joinmessages file to https://pastebin.com/tDCti9En.
2. See error: join messages are green (expected), but quit messages are &4, even though they use the same color code as join messages.

**Comment by OllieMartin** [comment]
This has been fixed, it was some very old legacy code preventing it from working 👍 
Will be released in the next beta of 1.10 (beta 4)
