### ISSUE TITLE
AsyncPlayerChatEvent error

### ISSUE THREAD

**Issue by notbike** [MultiChat/Development#139]
**Describe the bug**

One of the plugins i use is [QuickShop](https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/). every time i purchase an item from quickshop, this error pops out, even though the transaction was successful.

**Full startup log of affected servers**
```
https://pastebin.com/vC89qJVb
```

**To Reproduce**
1. Install a fresh copy of 'quickshop' and multichat
2. Start up version '366' of waterfall
3. start up 1.16 paperspigot server
4. create a shop with quickshop plugin by putting down a chest and hit the chest with the item you would like to sell in your main hand, enter how much you want to sell,
5. press enter, and then error will pop out
6. now that you have a shop, use another account to purchase an item from the shop by hitting the shop, enter how many items you would like to purchase.
7. press enter and the error will pop out again.
8. finish the transaction successfully

**Expected behavior**
I expect to finish the transaction successfully with no error in the console.

**Platform and Versions (please complete the following information):**
 - windows 10
 - java 8
 - MultiChat Version: 1.10-beta.4
 - Proxy Version: Waterfall-366
 - Local Server Version: paperclip-115

**error**
https://pastebin.com/bjynZuBD

**Comment by OllieMartin** [comment]
Hi there,

Thanks for the report! I will investigate the issue and let you know :)

**Comment by OllieMartin** [comment]
Fixed, will be released in the next 1.10 beta (beta 6 I beleive).

Thanks for the report :)

**Comment by notbike** [comment]
thank you martin for the fast reply! I appreciate your hard work！
