### ISSUE TITLE
Local channel and global channel showing different values for %DISPLAYNAME%

### ISSUE THREAD

**Issue by Mintaka3a** [MultiChat/Development#146]
Hello,

The placeholder %DISPLAYNAME% name displays perfectly in global chat, correctly picking up prefixes and suffixes defined in LuckPerms.

If I copy exactly the same format string into localconfig.yml for the "local_chat_format" value, %DISPLAYNAME% shows only the player name, without any prefix, suffix or colouring.

If I install EssentialsXChat and have it format the local chat, it does display the player name prefix and suffix correctly.

Is there any workaround for this? I'd like to avoid having two chat plugins installed.

**Comment by stw222** [comment]
do you have luckperms installed on both bungee and your spigot servers (or whatever permissions plugin you use. we do recommend luckperms)

if you do use LP, do all servers have access to the same database via mysql?

**Comment by Mintaka3a** [comment]
Thank you for the quick response! Yes, I can confirm that I have LuckPerms installed on both the Bungeecord and the collection of Spigot servers all using the same MariaDB database.  I don't use server specific contexts for any of my permissions or prefix/suffix definitions.

**Comment by stw222** [comment]
can you join our discord for better support?
https://discord.gg/PVreERC

**Comment by Mintaka3a** [comment]
For anyone else experiencing the same issue, stw222 was good enough to come up with a suitable workaround for this bug.

Although %DISPLAYNAME% shows prefixes and suffixes when used in the global chat format, you need to use %PREFIX%%NICK%%SUFFIX% to achieve the same result when populating the local_chat_format configuration value.
