### ISSUE TITLE
Clear nickname

### ISSUE THREAD

**Issue by chuushi** [MultiChat/Development#151]
**Is your feature request related to a problem? Please describe.**
There is no way to clear my nickname. The solution seems to be to name myself as my ign, but it does not help when I change my IGN through Mojang or when another plugin or the game sets the display name instead.

**Describe the solution you'd like**
I'd like something like /clearnick

**Describe alternatives you've considered**
Set the nickname as IGN, but see above

**Additional context**
I'm using a modpack where the nicknames are colored, and the modpack colored name never shows in chat.

**Comment by stw222** [comment]
if i remember right, you can use /nick [name] off

**Comment by Gadsee** [comment]
> 
> 
> if i remember right, you can use /nick [name] off
> although i could be wrong

This is correct. Relevant wiki page [here](https://github.com/MultiChat/Development/wiki/Local-Nicknames).
