### ISSUE TITLE
Chat content repeated in global chat and BungeeCord console

### ISSUE THREAD

**Issue by bobbyl140** [MultiChat/Development#153]
**Describe the bug**
I found this plugin and it is a perfect fit for my server! I looked at the wiki and configured everything, but I noticed one problem. Say there are two players, player1 and player2. If player1 is on server1 and player2 is on server2. player1 sends the chat message "hello.". player2 sees all the prefixes properly, but the message shows up as "hello.hello.". This also happens when the chat is shown in the console of the BungeeCord. I'm not 100% sure this is a bug, but nowhere in the configs could I find the way to format the BungeeCord console chat. 

**Full startup log of affected servers**
There are no errors or anything unusual produced in any of the 3 consoles (BungeeCord or the two Spigot servers)

**To Reproduce**
1. Install MultiChat on BungeeCord and at least two Spigot servers. 
2. Start the three servers
3. Join one Spigot server using one account, the other using another account. 
4. Say something to the chat using one account
5. Check the BungeeCord console as well as the chat on the other account.

**Expected behavior**
The chat message shouldn't be repeated, as this may confuse players.

**Screenshots**

**Platform and Versions (please complete the following information):**
 - OS: Windows 
 - Java Version: Java 11.0.8 2020-07-14 LTS
 - MultiChat Version: 1.9.5
 - Proxy Version: git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539
 - Local Server Version: git-Spigot-a19903d-5b74714

**Additional context**
I really love all this plugin does, and it is the perfect solution!

**Comment by stw222** [comment]
This is probably one of our known issues and can probably be easily fixed.
please join Multichat's Discord for help [https://discord.gg/PVreERC](https://discord.gg/PVreERC)
