### ISSUE TITLE
Chat listeners

### ISSUE THREAD

**Issue by Loonyy** [MultiChat/Development#16]
Hey man, great plugin. However, I'm having some issues with other plugins;

We have our own staff chat system that's activated through using @, we also have ChatReaction and FactionChat. These don't work, since it's not detecting that you entered <message> in chat to activate them. Also the same for colour chat with essentials. Is there a way around this?

Also, in one of my servers, I have it so that it shows the world they're in. Is there a way to enable this just for that server?

**Comment by Loonyy** [comment]
Also, is there a way so this plugin doesn't handle /nick, colour chat and other stuff?

**Comment by OllieMartin** [comment]
Hi there,
---
I am currently making an effort to sort out all the old issues reported with the plugin. Most of these are very old so will be marked as closed. If you still use the plugin and it is a valid error on the latest versions, then please open a new issue or get in touch with me. Thank you.
---

The issue with the @ symbol etc. is a known issue and is something I will be working to get rid of in future versions. Unfortunately, no bungeecord chatting plugin will work with what you describle (MultiChat, BungeeChat etc. etc.) Its just how they have to operate. I have an idea how to make a version of the plugin that will stop having this issue, but it requires a lot of re-writing. Hence why it is not going to be present in the new version 1.6 which is about to be released, but will be in the one after that (if I find a way to do so).

Colour chat etc. should all work, however EssentialsChat is a chat management plugin. MultiChat is also a chat management plugin. You cannot really use two of the same type of plugin, as they will conflict. Most of the time there are no issues between MultiChat and EssentialsChat, but it could be that you encountered one. If you still use the plugin at all then I'd suggest trying with the latest versions to see if this issue still persists.

Its not possible to create a chat format specifically for one world, but this kind of thing will again be present in future versions beyond 1.6. 

Apologies fo rthe awful response time, and lacking support, I have been working on the plugin a lot lately and am making a point to go through all the old issues for consistency.

Best Regards,
Oliver
