### ISSUE TITLE
Not loading/using chat format from config.yml??

### ISSUE THREAD

**Issue by ghost** [MultiChat/Development#17]
@OllieMartin 
It seems like MultiChat isn't loading the chat format from the config.yml for local chat, but is loading it for global chat. 

This is the format in the config.yml (the j's are for effect)
![chat snip 2](https://user-images.githubusercontent.com/28877233/29296362-5ecebee4-811f-11e7-96c1-fb85191fd0d1.PNG)
This is how it is formatted even after reloading the plugin and restarting BungeeCord/Spigot (with global chat off)
![chat snip 1](https://user-images.githubusercontent.com/28877233/29296371-6f97e408-811f-11e7-8d16-f6ee0495616b.PNG)
This is when I remove MultiChat from Spigot (to make sure MultiChat is formatting the chat)
![chat snip 3](https://user-images.githubusercontent.com/28877233/29296383-849df4a0-811f-11e7-9483-279428164880.PNG)
This is when I turn on global chat (it uses the format from the config.yml)
![chat snip 4](https://user-images.githubusercontent.com/28877233/29296386-88c81984-811f-11e7-9ddc-a62253d133be.PNG)

Thanks for making an awesome plugin!

**Comment by TortillaSquad** [comment]
I no longer have this issue. MultiChat still operates this way but I now use a different plugin for local chat formatting and I removed MultiChat from Spigot servers and use it only on BungeeCord for staff chat, global chat, and chat groups. 

This can be marked as closed if you like. Thanks!

**Comment by OllieMartin** [comment]
Hi there,
---
I am currently making an effort to sort out all the old issues reported with the plugin. Most of these are very old so will be marked as closed. If you still use the plugin and it is a valid error on the latest versions, then please open a new issue or get in touch with me. Thank you.
---
This is quite a weird looking error which I'm not sure I fully understand. The /local chat of the plugin works in a weird way, which was meant to keep it simple. This is something that will be changed in a later version (not 1.6 sadly), but the one after is likely. This will get rid of this issue and similar ones.

Sorry for the problem, and the awful response time.

Best Regards,
Oliver
