### ISSUE TITLE
chatitem | not work

### ISSUE THREAD

**Issue by KonoromiHimaries** [MultiChat/Development#20]
ss
![3a20fb9204a88c099b4e7d95d8a5b58d939dd600](https://user-images.githubusercontent.com/5884000/30241493-e26a05c8-9584-11e7-987a-0fd406bf3034.png)

chatitem plugin
https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/

timings
https://timings.aikar.co/?id=02444e1fb41b435aaf12cd49dcec3f3a

**Comment by OllieMartin** [comment]
Hi there,
---
I am currently making an effort to sort out all the old issues reported with the plugin. Most of these are very old so will be marked as closed. If you still use the plugin and it is a valid error on the latest versions, then please open a new issue or get in touch with me. Thank you.
---

This is a known issue with all BungeeCord chatting plugins that I know of.

This is just a compatibility issue between bungeecord chat plugins and spigot chat plugins, unfortunately it requires a huge amount of re-writing to the plugin. Other similar plugins like BungeeChat, FreeBungeeChat etc. will also all have this issue. I am working on a solution to this. It wont be in 1.6 which is about to be released, but the version after should debut new chat handling which will support all the plugins like this!

Apologies for the awful reponse time, I have been doing a lot of work on the plugin lately and am making a point of visiting all the old issues as a part of this.

Best Regards,
Oliver
