### ISSUE TITLE
/ignore <playername> | not work

### ISSUE THREAD

**Issue by mat41997** [MultiChat/Development#21]
essentialsx plugin
https://ci.drtshock.net/job/essentialsx/

**Comment by OllieMartin** [comment]
Hi there,

My apologies for the very slow reply, I am working through a backlog of messages and issues.

EssentialsX unfortunately as a Spigot plugin will not be able to control bungeecord enabled chat. You would need to find a bungeecord /ignore plugin! This is something I will be building into MultiChat in the near future.

Im sorry I cant be of more help!
