### ISSUE TITLE
spigot display name wont work

### ISSUE THREAD

**Issue by limegreenicy** [MultiChat/Development#23]
I recently updated my servers to 1.13 as well as all of the plugins. The only issue is, it grabs the chat format and such from multicraft, and doesn't display my PEX prefixes or anything. it's just the regular name and the chat.

**Comment by OllieMartin** [comment]
Hi there,

I am really sorry for the slow response, I'm not sure how I missed this issue.

Do you have Vault installed? This is a common fix for issues like this, otherwise I will investigate further.

Thanks for your patience, and my apologies again for the long wait
