### ISSUE TITLE
Prefix and Suffix Issue

### ISSUE THREAD

**Issue by MkZ0ck** [MultiChat/Development#31]
Hey, im currently having an issue that my prefixes and suffixes not get loaded in chat.
As I saw, the plugin get the prefixes from Vault cause it replaces my prefixes in the playerslist. So that works as acspacted. Tested the hole thing with diffrent versions. Tested with 1.6.1 and 1.6 of Multichat, running the newest version of Vault right now, tested also with an older one. Currently using spigot-1.12.2 and the newest BungeeCord Version. Rest of the plugin works perfectly fine. Tested with diffrent permissionsystems, tested with PEX and LuckPerms, same issue on both.

Hope that helps.
Greetins

**Comment by OllieMartin** [comment]
Hi there,
Sorry about this issue, it seems very strange! Could you please send me your config.yml file from MultiChat, and if you can also the full startup logs of both bungeecord and spigot.
Thank you!

**Comment by MkZ0ck** [comment]
[Logs_and_Config.zip](https://github.com/MultiChat/Development/files/2521592/Logs_and_Config.zip)

**Comment by OllieMartin** [comment]
Mmm, I can't see anything that would indicate a problem just from looking at that.

There are a couple of things you could try. If you turn "set_display_name" to true in the config, and replace the global chat format with "%DISPLAYNAME% &f:" does that work?

Also if you could send me a screenshot of what actually happens in the chat and console that would be helpful too.

Thanks, and sorry again for the issue. Its not something I've seen before.
