### ISSUE TITLE
Translation Support

### ISSUE THREAD

**Issue by Nogapra** [MultiChat/Development#36]
**Is your feature request related to a problem? Please describe.**
Adding a translation support feature

**Describe the solution you'd like**
In config.yml file Added line for support multiple language

for exemple language : FR-fr

This setting would change the language of the messages.yml and joinmessage.yml files If it exists in the original config

I'm aware that you need a team that can translate the files into multiple languages.
In any case I am ready to provide my French translations of the files messages.yml and Joinmessages.yml.

Sorry for the approximate English I am French and I use the Windows translator

Kind regards

**Comment by OllieMartin** [comment]
I confirm that I have seen this message and will be working to include the translations in the next update

**Comment by OllieMartin** [comment]
Translation files will be released with 1.7.1. To use the translations, simply rename the file to "messages.yml" or "joinmessages.yml"
