### ISSUE TITLE
Nicknames don't persist between server restarts

### ISSUE THREAD

**Issue by kencinder** [MultiChat/Development#39]
**Is your feature request related to a problem? Please describe.**
As per the title, nicknames are not persisting between server restarts.

Using the plugin on Waterfall along with the Sponge plugin on backend servers.

**Describe the solution you'd like**
Nicknames to be persistent

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by OllieMartin** [comment]
Apologies, there was a bug preventing the plugin from shutting down correctly. This is fixed in version 1.7.1 which I will release shortly :)
