### ISSUE TITLE
Chat format

### ISSUE THREAD

**Issue by Isolonice** [MultiChat/Development#4]
Hello,

Could you add "globalformat:" for Local chat please ? Useful to prefix that channel like:
- Global chat: [G] %DISPLAYNAME% :
- Local chat: [L] %DISPLAYNAME% :

With the 1.4 update the chat color prefixes are broken (with luckperm, idk for the rest). It shows the prefixe's color codes without "&", color doesn't apply like:
-  b[Prefixe] Name : 

Thanks !

**Comment by OllieMartin** [comment]
Yeah I'm sure I can sort out something for a local chat prefix :)

However; its very weird that your colours aren't working as Ive had no issues with luckperms or anything else. Could you send me your config and a screenshot of the console just so I can check some things? Thanks a lot and sorry for the issues!

**Comment by Isolonice** [comment]
Part of log bungee: http://pastebin.com/UBc6y3fJ

1:
- http://img4.hostingpics.net/pics/879886Capture.png
- globalformat: "[G] %DISPLAYNAME% : "

2:
- http://img4.hostingpics.net/pics/351819Capture.png
- globalformat: "&6[G] %DISPLAYNAME% : "

**Comment by Isolonice** [comment]
Solved colors using unicode instead of section character. Tried encoding utf8 on multiple way without success: "§" = > "\u00A7":
- SpigotComm.java:[117,87]
- SpigotComm.java:[133,238]
- BungeeComm.java:[57,100] 
- BungeeComm.java:[58,117]
- ChatStream.java:[242,66]

**Comment by OllieMartin** [comment]
Okay Ive just got home so Im going to try and fix this :)

Im gonna set up luckperms etc. to try and replicate your issue, I know the kinds of things that could cause the issue but its weird that it hasnt affected any of the other servers Ive seen the plugin working on

**Comment by OllieMartin** [comment]
Also when you said you used unicode what symbol were you referring to?

**Comment by OllieMartin** [comment]
Were you using the § symbol for colour codes? I can only re-create your issue if paste that in instead of &? The way the plugin works is it takes any & colour codes and converts the display names to use § as that is how it is interpreted by most plugins. I do all my processing after converting the color codes to start with §. Ive got the latest version of luckperms and multichat and I cant seem to make it break :/

**Comment by OllieMartin** [comment]
I have however implemented this for you! https://puu.sh/urbWv/ac0725e8d6.png

The way it works is that in the global format you can specify %MODE% which will become either "Global" or "Local", or %M% which will become "G" or "L" :)

**Comment by Isolonice** [comment]
Just for meh ! Thanks =D

I'm not using this symbol, it's in the source code where i replaced to make it works. I'll try again, maybe i missed something.

**Comment by OllieMartin** [comment]
Yeah try the version I just posted in case it fixes it.

So you in the code replaced "§" for "\u00A7"? Weird how that would work instead :S As I said Ive seen the plugin working on multiple servers so I found it surprising it was giving you errors :/

**Comment by Isolonice** [comment]
Hello,

I tried the lastest jar and it's working very well ! Thanks :)

So i changed again some lines (just translation) and i got this color problem again. Then i tried to compile it without changes and i got it too. I've done "mvn package / mvn clean package / mvn build" and i get a different size of compiled .jar. Am i doing something wrong ? Anyway you can close this it is not an issue anymore :p

**Comment by OllieMartin** [comment]
Great! :)

And that does seem very weird, Maven clean and Maven install are what I do when re-building it so what you are doing seems fine to me! When I release 2.0 all the messages will be totally configurable so you wont need to worry about editing the code for translations in the future :)

Sorry about that, if you need anything else then please let me know!
Thanks a lot, ~Ollie
