### ISSUE TITLE
Nickname blacklist and inability to impersonate another user

### ISSUE THREAD

**Issue by kencinder** [MultiChat/Development#40]
**Is your feature request related to a problem? Please describe.**
There doesn't appear to be a way to block the use of certain nicknames, or stop users from setting nicknames of other users to impersonate them.

**Describe the solution you'd like**
A nickname blacklist ability, as well as the inability to set your nickname to that of another players username.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by OllieMartin** [comment]
I will look into this, I need to release version 1.7.1 to fix the error with nicknames not saving correctly, but maybe will get this done for a 1.7.2 :)

**Comment by Nogapra** [comment]
Ok

**Comment by OllieMartin** [comment]
Fixed in version 1.7.2 :) https://www.spigotmc.org/resources/multichat.26204/update?update=271095
