### ISSUE TITLE
Translations directory format

### ISSUE THREAD

**Issue by kencinder** [MultiChat/Development#42]
**Describe the bug**
Translations directory is being created as `MultiChat\translations` rather than what I assume intended, was for a sub-directory of `translations` in the `MultiChat` directory.

Doesn't affect a Linux server, but if done on windows this may break things.
`\` in a file/dir name is illegal on Windows. Although this may result in the creation of said sub-directory on Windows...did not test to see.

**Platform and Versions (please complete the following information):**
 - OS: Debian 9.5
 - Java Version: OpenJDK 64-Bit Server VM, version 1.8.0_181
 - MultiChat Version: 1.7.1
 - Proxy Version:  Waterfall-Bootstrap:1.13-SNAPSHOT:1732f85:258
 - Local Server Version: N/A

**Additional context**
N/A

**Comment by OllieMartin** [comment]
Many thanks for your report! Indeed it does create a directory on Windows, I had neglected to consider other file systems when coding this part! I'll get it fixed for 1.7.2 which I hope to release soon :)

**Comment by OllieMartin** [comment]
Fixed in version 1.7.2 :) https://www.spigotmc.org/resources/multichat.26204/update?update=271095
