### ISSUE TITLE
One quick questions...

### ISSUE THREAD

**Issue by Stokykyle** [MultiChat/Development#6]
Is there a way to do different Rank/Group formating like in essentials.

**Comment by OllieMartin** [comment]
Hey,

By this I asssume you mean like in the config where you do:

default: &f%DISPLAYNAME%:
admin: &4<<< %DISPLAYNAME &4>>>>&c:

or something similar?

Multichat doesnt offer this as there are so many different plugins that use ranks etc., but the way you can get around it is by using a permissions plugin which lets you set prefixes and suffixes like 99% of them do, then you can just adjust the prefix and suffix for each rank to however you want it to show up in the chat, MultiChat will then pick up this information from vault if you install that and display it in the global chat :)

If you have any other questions just let me know!
