### ISSUE TITLE
Send messages to channels instead directly for the players

### ISSUE THREAD

**Issue by Eufranio** [MultiChat/Development#67]
I've tried to listen the chat messages on Sponge but seems that the messages are sent directly to the players, so there's no way any Sponge plugins could listen to them. What I suggest is that instead sending directly to the player, send to a plugin channel a message containing the destination player UUID and the message, and the backend servers would send manually the message, possibly firing events or so. This would allow us to have control over the messages sent via this plugin.

**Comment by OllieMartin** [comment]
Hi there,

I know this is an exceptionally old issue but I have been doing a load of refactoring on the local sponge part of the plugin.

I believe that how I have changed this listener in the development versions would now facilitate other plugins being able to see the MultiChat messages? https://github.com/MultiChat/Development/blob/7e4ca11501a920bfa7d0ce8ecb1d39e1cb3da838/multichat/src/main/java/xyz/olivermartin/multichat/local/platform/sponge/listeners/chat/LocalSpongeChatListenerHighest.java#L56

**Comment by OllieMartin** [comment]
I have tested this with MagiBridge in vanilla mode, and MultiChat no longer prevents magibridge from logging the chat as it normally would. So there is now a basic level of support there.
