### ISSUE TITLE
Add %GROUP_META_XXXX% and %USER_META_XXXX% placeholder

### ISSUE THREAD

**Issue by HHServers** [MultiChat/Development#68]
**Is your feature request related to a problem? Please describe.**
I need a placeholder that reads a users Meta values for easier addition of extra prefixes from certain plugins that don't use the typical prefix.1.X way of adding prefixes.

**Describe the solution you'd like**
A placeholder that reads either group or user meta and shows the value of the meta key
**Describe alternatives you've considered**
PlaceholderAPI but does not offer LuckPerms support for Sponge

**Comment by OllieMartin** [comment]
I think that for now this is beyond the scope of the plugin. Have you considered: https://ore.spongepowered.org/Nurdism/LuckHolders

I won't rule out adding it, however I think a solution might already exist in the above plugin. I have used luckperms placeholders in Sponge before with PAPI.
