### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by superpurplegamer** [MultiChat/Development#69]
Hello creators.
I have an issue with the permissions. I use the plugin permssionsex which is hooked up to mysql. I have all the perms but whenever i do one of your commands (except /nick for some reason) It says i have no permissions. I tried giving it manually but it didn't work either. I have no idea what is causing this, but i hope you can help me.

**Comment by fnutt** [comment]
PEX does not support BungeeCord, and MultiChat is a BungeeCord plugin. Also, PEX is old and rubbish.

Worlds moves forward, so should you. Use LuckPerms!
https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/
