### ISSUE TITLE
global/local chat format

### ISSUE THREAD

**Issue by digitronics** [MultiChat/Development#7]
Awesome plugin! Loving it so far. 2 things tho, it would be nice to be able to have a format for local & global chat. IE, 
`globalformat: "&7[&f%SERVER%&7] &r%DISPLAYNAME%&r: "`
`localformat: "%DISPLAYNAME%&r: "`

**Comment by digitronics** [comment]
I ended up making a few modifications to the plugin, I organised the code a bit and added `localformat` & `globalformat` options. I'd highly recommend organizing the classes to make it easier to work with. Anyways if you want to take a look at the changes [here's the repo](https://github.com/digitronics/multichat)

**Comment by OllieMartin** [comment]
Hey!

The reason I haven't gone in depth with things like that yet is that in 2.0 Im overhauling how all the chat works and adding in the option to have completely customisable chat streams etc which will all have their own formats and will make the whole process of having local chats easy etc.

And yes I am very aware of the... um... mess... of code that I have. I started coding it as a high school student who barely knew Java and didn't know any naming conventions or anything, and now I study computer science at university and our course specialises in Java, so it pains me to look back on my horrible code! I can assure you for 2.0 I will be making it all nice and clean!

And thanks for the link to the repo, I have no issue with people editing the code like you did and its great that you let me know you did so as well :) 

So yeah Im afraid I wont be implementing that separate format specifically, but It will work out much better for you when I finally can get 2.0 done :)

If you have anything else you need just let know!
