### ISSUE TITLE
Optional console logging

### ISSUE THREAD

**Issue by fnutt** [MultiChat/Development#70]
**Is your feature request related to a problem? Please describe.**
Due to GDPR and privacy concerns my network have issues related to logging messages that are seen as private. This includes private messages between players and group messages. MultiChat logs all messages on both Spigot/Paper and BungeeCoord/Waterfall level.

**Describe the solution you'd like**
Add %MESSAGE% to https://github.com/MultiChat/Development/blob/master/multichat/src/main/resources/messages.yml#L21-L28 message template, or add config for each console message true/false in https://github.com/MultiChat/Development/blob/master/multichat/src/main/resources/config.yml

**Comment by OllieMartin** [comment]
Consider it done, there will be options to disable private message logging, group chat logging, and staff chat logging in the config file :)
