### ISSUE TITLE
Feature request: Localspy

### ISSUE THREAD

**Issue by FaberoM** [MultiChat/Development#75]
An ability to see chat messages from every server. It would work like /socialspy except for local chat messages.

This would be very useful in moderating the chat as our moderators cannot be on every server at the same time.

**Comment by OllieMartin** [comment]
I will try and implement this soon. It won't be in the initial release of v1.8, but could be in a 1.8.1 or 1.8.2 potentially! I will see what I can do :)

**Comment by OllieMartin** [comment]
This will be added in v1.10 ( as long as all goes to plan! ) :)

**Comment by OllieMartin** [comment]
This has now been added in 1.10. It will be present whenever the update is released. Hopefully not too long.

**Comment by FaberoM** [comment]
Thank you, good luck with the rest of the update!
