### ISSUE TITLE
Waterfall: Prefixes and Suffixes not working properly with Luckperms Bungee & MultiChat

### ISSUE THREAD

**Issue by LinuxSquare** [MultiChat/Development#76]
**Describe the bug**
the Prefix and Suffix is not showing up, instead just the placeholders [%PREFIX% Username %SUFFIX%](https://i.imgur.com/YOaWgwL.png).

Prefixes and Suffixes are set using LuckPerms Bungee.
Permission set using LP Bungee are working fine.

**Full startup log of local servers**
```
[MultiChatSpigot] [ERROR] Vault was found, but will not work properly until you install a compatible permissions plugin!
```

**To Reproduce**
1. Install a fresh copy of 'Multichat' in Bungeecord
2. Install a fresh copy of 'Multichat' in local Server
3. Install a fresh copy of 'Vault' in local Server
4. Install a fresh copy of 'LuckPerms Bungee'
5. Start up version 'waterfall-327' of Bungeecord
6. Start up version 'paper-161' of PaperSpigot
6. Type something in chat
7. See [image](https://i.imgur.com/YOaWgwL.png)

**Expected behavior**
The Prefixes and Suffixes should work fine, using LuckPerms as a Bungee Plugin

**Platform and Versions (please complete the following information):**
 - OS: `Debian GNU/Linux 10 4.19.0-6-amd64`
 - Java Version: `openjdk version "11.0.5" 2019-10-15`
 - MultiChat Version: `1.7.5`
 - Proxy Version: `waterfall-327`
 - Local Server Version: `paper-161`

**Additional context**
* I have tried to add EssentialsX to the local Server but it didn't work either.
* I have tried to add Vault to the plugins folder of Bungee (wasn't a good idea)
* I have removed LP from Bungee and added it to the local Servers (Prefixes and Suffixes worked with ease)

**Comment by Spacelord09** [comment]
Hey just install the LuckPerms plugin on your slave servers.

**Comment by LinuxSquare** [comment]
Good Morning

Thanks to @Spacelord09 for the tip.
But that's not everything.

I forgot to configure the plugins, so that they accessed the same database.
Now it's all up and running and syncing between the slave servers and bungee.

Thank you for your help.

**Comment by Spacelord09** [comment]
No problem!
