### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by Spacelord09** [MultiChat/Development#78]
**Describe the solution you'd like**
MySQL database for logging mails( #77 ) and everything else ;D

**Comment by OllieMartin** [comment]
MySQL is partially added in v1.8. It will be used for MultiChatSpigot and MultiChatSponge to sync nickname data betweens servers if you wish. This is the first step towards full MySQL and SQLite support. Version 1.9 will hopefully migrate all parts of the plugin to use this system and will likely also add things like mail :)

**Comment by Spacelord09** [comment]
Can you add a global /nick command too then?

**Comment by OllieMartin** [comment]
It isn't necessary to change how /nick works. If you set up MySQL then when you set a nickname it will act like a global nick because it will sync to all the servers connected to that MySQL database :)
