### ISSUE TITLE
Shortcut to send messages in a different channel without the need to switch channels.

### ISSUE THREAD

**Issue by Spacelord09** [MultiChat/Development#79]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i need to change my channel to global for a reply.

**Describe the solution you'd like**
I would like a "/g [MESSAGE]" command to send something in the global channel.
Or "/l [MESSAGE]" for the local channel.
The whole thing adds a lot to the usability, because you don't have to change channels just to send a response to another channel.

**Comment by OllieMartin** [comment]
I am trying to get this feature into 1.8, but it is actually a lot harder than it might seem. The reason I didn't implement that in there to start with is because of how tricky it is. Ill see what I can do!

**Comment by OllieMartin** [comment]
Its a pain as I thought, but it will be in version 1.8! It let me find a few bugs though so that is always good!

**Comment by Spacelord09** [comment]
Thank you! Can you look at my other issues?

**Comment by OllieMartin** [comment]
Yes I have looked at all isues. I don't want to overload a single version of the plugin with too many new features though. I am taking them one at a time and deciding what makes most sense for me to add at each point :)

Thank you for all the suggestions though, I appreciate it!
