### ISSUE TITLE
Plugin Doesn't Change Prefix & Display name

### ISSUE THREAD

**Issue by MGKPartyBoy** [MultiChat/Development#8]
I downloaded the MultiChat plugin and I installed it into Bungee along with each of my indivial servers. I enabled the option in the config to grab display names from Spigot / Craftbukkit. Still didn't work.

Using Essentials Group Manager + Multichat
Error: https://pastebin.com/hgdaaN4B

**Comment by OllieMartin** [comment]
Hey there sorry its not working for you!

Can I ask which version of Bungeecord you are using? I was under the impression the old displayname length limit was only on older versions of bungee. Try updating it if you are on an older version and see if that works :)

Also I assume you have vault installed? If not that could help you out :)

That error while being thrown as a result of my plugin handling the message isn't actually something I coded, its something from the bungeecord code limiting display name length. I shall have to have a look at my code to see if I can spot anything that could be an issue :)

**Comment by MGKPartyBoy** [comment]
I am running a version of bungee that supports Minecraft 1.7.10 - 1.10.2. I forgot which version it was, but I know it's not the most recent one. I would update, but we're running some 1.7.10 servers which means we can't update to the newest version of bungee.

I have vault installed on every server, but not on the bungee server itself, is this a problem?

Anything you could say to point me in the right direction would be great. Thanks

**Comment by MGKPartyBoy** [comment]
Didn't mean to close, Just to comment! :)

**Comment by jon100456** [comment]
Hello i am having the same problem!
Using Vaults Latest version: 1.5.6 and tried 1.5.5
I am also using Bungeecord 1.7-1.11 Version: v132 
Link to the bungeecord i am using: https://github.com/HexagonMC/BungeeCord/releases"
I also use EssentialsX and GroupManager together they work fine without MultiChat
i see the prefix that i set in groupmanager once i install MultiChat i do not see it 
i do have BungeeCord Errors: https://pastebin.com/VZjsVVKb i hope this information can fix this problem thank you

**Comment by OllieMartin** [comment]
Hey there guys,

Very sorry for such a slow reply but I have had so much work as of late.

I have looked through this issue as its something I have seen before. As you can see this error was revoked by md5 in this commit: https://github.com/SpigotMC/BungeeCord/commit/8b327708ee32276ed0b74527d899903a19300f3e

If you are using a version of bungeecord older than this commit I'm afraid there is nothing I can do as its an issue in BungeeCord itself not MultiChat :/

Please do get back to me with how it goes and again sorry for the delay!
