### ISSUE TITLE
nickname prefix appears despite not having a nickname

### ISSUE THREAD

**Issue by stw222** [MultiChat/Development#83]
I am creating this on behalf of Fabian Adrian #6234 on discord

**Describe the bug**
The nickname prefix appears despite not having a nickname (using /nick off)

when `show_nickname_prefix` is false, the prefix isn't there

**Full startup log of affected servers**
Paper startup log: https://pastebin.com/8LBtexDe
Waterfall startup log: https://pastebin.com/MQJLzwWw

**To Reproduce**
Make sure show_nickname_prefix is true

**Expected behavior**
The prefix should not appear if you don't have a nickname

**Screenshots**
![image](https://user-images.githubusercontent.com/37747659/78738557-267f1b00-7920-11ea-8674-b32a8717c8de.png)

![image](https://user-images.githubusercontent.com/37747659/78738580-339c0a00-7920-11ea-8280-1209b2c420ef.png)

**Platform and Versions (please complete the following information):**
 - OS: CentOS 8
 - Java Version: Oracle 1.8.0_241
 - MultiChat Version: 1.8
 - Proxy Version: Proxy: Waterfall-327
 - Local Server Version: 1.15.2 (Paper-162)

**Additional context**
Spigot config: https://pastebin.com/AXVyQCpY
Bungee config: https://pastebin.com/vfuGwgn4

https://discordapp.com/channels/481484944942694401/481492509067968512/697260012925485077 (in the multichat discord)

**Comment by OllieMartin** [comment]
Thank you, this is fixed in v1.8.1 due for release today
