### ISSUE TITLE
error with mce regex [i purposly only used * instead of .*]

### ISSUE THREAD

**Issue by stw222** [MultiChat/Development#89]
**Describe the bug**
player executed command: /mce -s * [command]

https://pastebin.com/9MS1DGE6

**Full startup log of affected servers**

https://pastebin.com/UphwEPR4

**To Reproduce**
use /`player executed command: /mce -s * [command]`
specifically with only * instead of .*

**Expected behavior**
maybe make a message saying that this wont work instead of an ugly error

**Screenshots**

**Platform and Versions (please complete the following information):**
Java: 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
MC ver: 1.8.1
Proxy Ver: Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326
Local Ver: 1.15.2 paper-162

**Additional context**

**Comment by OllieMartin** [comment]
https://i.imgur.com/lZuXYgZ.png

This has been fixed in the development builds :)
