### ISSUE TITLE
[Feature] tooltips 

### ISSUE THREAD

**Issue by jon100456** [MultiChat/Development#9]
can you add tooltips like the way DeluxeChat plugin works 
https://www.spigotmc.org/resources/deluxechat.1277/ 
it would be great if you can add it too MultiChat because when player use nickname it can be hard when your on a different server then that player to see what there realname by using this feature it can help greatly thanks

**Comment by bumblebeesapps** [comment]
This is exactly what I would like to see. The only reason why I haven't switched to this chat yet. is there maybe a way to make the text clickable so it would fill out like "/msg Name"

**Comment by OllieMartin** [comment]
Hey guys, sorry for the delay!

Unfortunately this isn't a simple thing to add! Version 2.0 will be coming this Summer so this is definitely something I will consider for you guys, but with my amount of work currently I do not have time to get it into version 1.4.1. Thanks for the suggestion though and I will see what I can do :)
